### ISSUE TITLE
investigate using CSS attribute selectors

### ISSUE THREAD

**Issue by afeld** [18F/private-eye#12]
Rather than adding a class to each private link, what if the config generated CSS that achieved the same thing?

``` css
a[href~={{url}}] {
  /* styles */
}}
```

Suggestion by @andrewmaier.

**Comment by rahearn** [comment]
I'm unsure that this would be helpful, since you would still need the double loop being currently used in order to set the title text.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
