### ISSUE TITLE
link to the repository (and instructions) from the demo site

### ISSUE THREAD

**Issue by afeld** [18F/private-eye#15]
[Demo site](https://pages.18f.gov/private-eye/)

This could be done via a [GitHub Ribbon](https://github.com/simonwhitaker/github-fork-ribbon-css) (with the assets copied into this repo, instead of using the CDN), or a simple link in the text somewhere.

**Comment by awayken** [comment]
@afeld Is the Demo site its own repository? I don't see any files in this repository that would create the demo page.

**Comment by afeld** [comment]
Good question! (That would be a good thing for us to add to `CONTRIBUTING`.) They are in the [`18f-pages`](https://github.com/18F/private-eye/tree/18f-pages) branch.
