### ISSUE TITLE
Replace "private link" example

### ISSUE THREAD

**Issue by thecapacity** [18F/private-eye#18]
In the description page; https://pages.18f.gov/private-eye/
    - Would it be possible to replace the "... throwup a [private link](http://so.me/private/url)" with something like [private link](https://pages.18f.gov/private-eye/notfound)

I couldn't easily find the home page or I would have issued a PR.

**Comment by afeld** [comment]
> Would it be possible to replace the "... throwup a [private link](http://so.me/private/url)" with something like [private link](https://pages.18f.gov/private-eye/notfound)

Ha, didn't even consider that so.me was an actual domain. Sure! I'd use `/private` or something.

> I couldn't easily find the home page

See the `18f-pages` branch.

**Comment by thecapacity** [comment]
Awesome @afeld thanks for the pointer on the branch (I forgot github pages did that for one of its hosting model) -- PR issued.
