### ISSUE TITLE
add automated tests

### ISSUE THREAD

**Issue by afeld** [18F/private-eye#4]
e.g. using [Mocha](https://mochajs.org/#running-mocha-in-the-browser) + [mocha-phantomjs](https://github.com/nathanboktae/mocha-phantomjs).
- [x] Build on CI

**Comment by noahpryor** [comment]
Possible test cases

- Links that include a url string from ignoredUrls should have the class `private-link` added
- Matching links without a `title` attribute should have the `defaultMessage` added as the title 
- Matching links with a `title` attribute should only have the class `private-link` added
- If a `defaultMessage` is option is set, it should be be used be added to matching links
- If a `defaultMessage` options is not set, the message should be "This is a link to a private site, which may or may not be accessible to you."
- ignoreUrls can take either an array of strings or an array of objects with `{message:, url:}`
- when a specific message is set for a given url in `ignoredUrls` and the link doesn't have a title tag, it should use that message for the title tag
- (If #23 is merged) url matching is case insensitive 
Definitely don't love the way I phrased these, but I think this is all of the core functionality

**Comment by afeld** [comment]
Closing since the base objective is one, but would love to go back and add more of those tests.
