### ISSUE TITLE
a way to make this a bookmarklet?

### ISSUE THREAD

**Issue by gbinal** [18F/private-eye#6]
In thinking about how to add directions for the non-technical to use, I wonder if it'd be hard to make this a bookmarklet that someone could activate just by clicking on it.

**Comment by afeld** [comment]
Hmm. It's an interesting idea, though the plugin isn't useful (in its current state) without configuring what the private domains are, so not sure that it would actually help for the user to activate it (versus one of the site administrators). Closing for now, but if anyone has ideas about how it could work, we can certainly reopen!
