### ISSUE TITLE
exclude unnecessary files from module

### ISSUE THREAD

**Issue by afeld** [18F/private-eye#8]
Relevant after https://github.com/18F/private-eye/pull/7 is merged. Not sure what the best practice is around, for example, whether files like the README and the related assets should be distributed or not... `package.json` and `private-eye.js` are the only files that are _really_ needed. Would love input from others.

**Comment by rogeruiz** [comment]
Taking a look at some `node_modules` in my `/usr/local/lib/node_modules` directory, I'm seeing that most packages include all the files that you currently have in the `master` branch. I think it's okay to include `README`, `LICENSE`, `CONTRIBUTING` along with others in the future such as `test/`once #4 is complete. Maybe this issue can be resolved by adding a script hash with a `postinstall` property that generates a `dist` directory with just the files needed to run, in this case `private-eye.js`.

#### Example below of two `node_modules` `through` & `strftime`

```
node_modules
├── [ 306]  through
│   ├── [ 238]  test
│   │   ├── [2.3K]  index.js
│   │   ├── [ 707]  end.js
│   │   ├── [1.5K]  buffering.js
│   │   ├── [ 516]  auto-destroy.js
│   │   └── [ 629]  async.js
│   ├── [1.6K]  readme.markdown
│   ├── [1.6K]  package.json
│   ├── [1.1K]  LICENSE.MIT
│   ├── [2.6K]  index.js
│   └── [ 586]  LICENSE.APACHE2
├── [ 340]  strftime
│   ├── [ 102]  test
│   │   └── [6.3K]  test.js
│   ├── [7.5K]  strftime.js
│   ├── [1.7K]  package.json
│   ├── [ 232]  component.json
│   ├── [4.5K]  Readme.md
│   ├── [ 344]  Makefile
│   └── [3.2K]  strftime-min.js
```

**Comment by rogeruiz** [comment]
Taking a further look at the npm documentation under [`npm-developers`](https://docs.npmjs.com/misc/developers#link-packages), it seems like certain files are included no matter what. Scroll up after clicking that link since the section I've included below isn't anchored to anything.

> The following paths and files are never ignored, so adding them to .npmignore is pointless:
> - package.json
> - README (and its variants)
> - CHANGELOG (and its variants)
> - LICENSE / LICENCE

Including an `.npmignore` file should remedy any files that shouldn't be published for whatever reason.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
